// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq858JHwTssXbsHfPHnHCrz4Mx8YFnsAE',
    appId: '1:1033481879670:web:a15b17a1b8e06f74fe5f57',
    messagingSenderId: '1033481879670',
    projectId: 'movie-search-app-84830',
    authDomain: 'movie-search-app-84830.firebaseapp.com',
    storageBucket: 'movie-search-app-84830.appspot.com',
    measurementId: 'G-HDLYGF3HN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASOC1sw1e8qNGrOUMxKymSZ5VqQCVXS6I',
    appId: '1:1033481879670:android:379ccc176b570fe7fe5f57',
    messagingSenderId: '1033481879670',
    projectId: 'movie-search-app-84830',
    storageBucket: 'movie-search-app-84830.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbggICiCX0DEKqMlpz9NkSEu-i56a1tpE',
    appId: '1:1033481879670:ios:578f35e0350b90fbfe5f57',
    messagingSenderId: '1033481879670',
    projectId: 'movie-search-app-84830',
    storageBucket: 'movie-search-app-84830.appspot.com',
    iosClientId: '1033481879670-37tlasg515ghlqjk7io4n852o106lm7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.madProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbggICiCX0DEKqMlpz9NkSEu-i56a1tpE',
    appId: '1:1033481879670:ios:b4802eca08891d71fe5f57',
    messagingSenderId: '1033481879670',
    projectId: 'movie-search-app-84830',
    storageBucket: 'movie-search-app-84830.appspot.com',
    iosClientId: '1033481879670-vhgks2v8itioh6vum0mbqr867iip190h.apps.googleusercontent.com',
    iosBundleId: 'com.example.madProj.RunnerTests',
  );
}
